### ISSUE TITLE
it wont compile

### ISSUE THREAD

**Issue by guizinhomartinez** [EIT0/PE-tutorials#2]
![image](https://user-images.githubusercontent.com/81656897/167520596-4d5508c1-f9e4-4f35-b0c2-fd364ae40fc8.png)
i think you forgot to add a file cuz there isn't a file called worldstate

**Comment by sonicfan888** [comment]
had the same issue but i tried to fix it and i kept getting some errors

**Comment by sonicfan888** [comment]
> I didn't forgot, the code is for another tutorial, I forgot to remove it when uploading, just delete the switchState

I tried to delete the switchState and i still get errors

**Comment by sonicfan888** [comment]
update:
i fixed it
just do MusicBeatState on line 343, nothing else really

**Comment by EIT0** [comment]
you just messed the most essential thing of the game

**Comment by EIT0** [comment]
suggest you to just delete the state redirects on the second category and re install MusicBeatState
