### ISSUE TITLE
Eit, you just merged stolen code.

### ISSUE THREAD

**Issue by Gabriel2019r** [EIT0/PE-tutorials#23]
@EIT0, why did you put a stolen code to your repository? WHY?
![image](https://user-images.githubusercontent.com/100803757/181345486-f219a8c0-805b-411e-9155-cfdf03be7506.png)

**Comment by Gabriel2019r** [comment]
I am very dissapointed in you.

**Comment by hatsaregood** [comment]
Eit, you just merged stolen code.*
please rename it to this

**Comment by Gabriel2019r** [comment]
why would you put it in your repo?

**Comment by hatsaregood** [comment]
there we go, better name

**Comment by Gabriel2019r** [comment]
![image](https://user-images.githubusercontent.com/100803757/181346452-907c2480-1251-4f57-82ef-77d90e001f7b.png)

**Comment by Gabriel2019r** [comment]
![image](https://user-images.githubusercontent.com/100803757/181346497-c6e9beb6-e9c9-4fd6-9826-ea1763be0fa0.png)

**Comment by hatsaregood** [comment]
also the fact hayden did nothing but change 2-1 lines of code, YET YOU STILL MERGED IS STUPID AS HELL, I CAN EVEN MAKE A FREEPLAY STATE BETTER THAN YOU

my response: your code is the worst :skull:

**Comment by REALHaydenGaming** [comment]
Lemme get this straight:
THIS IS A MODIFIED VERSION I GOT DONE, IN 30 MINUTE'S.
If you could take the time and look: They are the same, I just somehow replicate the "haha funny vs dave revenge 3.5" transition, it actually wasn't hard to make.

**Comment by EIT0** [comment]
shit, i didnt knew so, i am going to fully change it rn, hope this fixes it

**Comment by REALHaydenGaming** [comment]
@EIT0 if you need proof this is a modification version of it, dm me please
