### ISSUE TITLE
build error on latest version of psych 

### ISSUE THREAD

**Issue by TylerTehIdiot** [EIT0/PE-tutorials#25]
![Screenshot_20220729-215431](https://user-images.githubusercontent.com/93739827/181865892-ae0e4520-228c-4c1b-818b-f25d7f86484d.png)

**Comment by REALHaydenGaming** [comment]
Tutorials were made using psych engine 0.5.2h.

**Comment by REALHaydenGaming** [comment]
Meaning they probably don't work with PE 0.6.2.

**Comment by REALHaydenGaming** [comment]
And some of the stuff is EVEN FROM 0.4.2.

**Comment by EIT0** [comment]
Those errors arent bc you are using theblatest version
