### ISSUE TITLE
Why is this happening

### ISSUE THREAD

**Issue by KadePleaseHelpMe** [EIT0/PE-tutorials#3]
![image](https://user-images.githubusercontent.com/89645987/167670364-9481dc34-1df8-42c2-9113-2fb4eaf5cb87.png)
![image](https://user-images.githubusercontent.com/89645987/167670436-bea33b43-e330-4f85-b451-7dcc2bfc5f81.png)

**Comment by EIT0** [comment]
import FlxBackdrop

**Comment by EIT0** [comment]
import FlxBackdrop

**Comment by KadePleaseHelpMe** [comment]
Ey! Thank you, EIT!

**Comment by KadePleaseHelpMe** [comment]
(closed)

**Comment by KadePleaseHelpMe** [comment]
![image](https://user-images.githubusercontent.com/89645987/167746756-ed29140a-da11-47b9-bac7-22a8bb2552a9.png)
Uh oh...

**Comment by KadePleaseHelpMe** [comment]
wait I found it
![image](https://user-images.githubusercontent.com/89645987/167746847-e8456277-a941-410e-93db-9b4f183bd67d.png)
