### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by MateoSorianoGi** [EIT0/PE-tutorials#6]
![image](https://user-images.githubusercontent.com/46869173/168385865-93610ffc-f890-4472-9cc2-f56f06c5983b.png)
![image](https://user-images.githubusercontent.com/46869173/168385881-dce0abe1-d6df-4367-b64e-10a3d0698dbd.png)
![image](https://user-images.githubusercontent.com/46869173/168385887-504178c0-b9fb-485d-8974-930ff5253970.png)

**Comment by guizinhomartinez** [comment]
he didn't add to lua so you will have to add it

**Comment by MateoSorianoGi** [comment]
> he didn't add to lua so you will have to add it

idk wheres the code

**Comment by EIT0** [comment]
bruh, i didnt added it on lua, just add it on source code + adding it on lua is really easy

**Comment by MateoSorianoGi** [comment]
> bruh, i didnt added it on lua, just add it on source code + adding it on lua is really easy

i added it but it doesnt work
