### ISSUE TITLE
"to many arguments"

### ISSUE THREAD

**Issue by Razthefunni** [EIT0/PE-tutorials#8]
![image](https://user-images.githubusercontent.com/98192860/170871647-f3979802-85c1-4554-aba3-a2dc6138b580.png)
 says for some reason theres "to many arguments" idk why i didn't edit it at all

**Comment by Razthefunni** [comment]
and if i try to remove 1/2 of them i just makes the arrows smaller

**Comment by TylerTehIdiot** [comment]
did you ever fix this bc I'm having the same problem

**Comment by mji1010** [comment]
i have the same too

**Comment by TylerTehIdiot** [comment]
How did you fix it?

**Comment by TylerTehIdiot** [comment]
> but i fix it and now i have others files fix but idk how

Can you at least upload the source

**Comment by EIT0** [comment]
show me the code

**Comment by TylerTehIdiot** [comment]
> show me the code

https://github.com/TylerTehIdiot/Psych-Tutorial-Test

**Comment by EIT0** [comment]
you modified something on Note.hx
